# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-lint-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        'node-version': [12.x]
        # node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix['node-version'] }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix['node-version'] }}

      - name: lint
        run: |
          npm install -g @stoplight/spectral
          find ./ -name '*.yaml' | xargs -Ixxx spectral lint -F warn xxx

      - name: Create static API doc
        run: |
          npm install -g redoc-cli
          for i in `ls public`; do redoc-cli bundle -o `echo dist/${i}.html | sed 's/yaml.//'` public/$i; done

      - name: Create dist/index.html
        run: |
          cat app/head.txt > dist/index.html
          for i in `ls dist | grep -v index.html`; do echo \<li\>\<a href="${i}"\>${i}\</a\>\</li\>; done >> dist/index.html
          cat app/tail.txt >> dist/index.html
          cat dist/index.html

      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: redoc_specs_dist
          path: dist

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=./dist --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}




